version: '3'
services:
  api:
    build: .
    env_file: .env
    ports:
      - 80:80
    depends_on:
      - minio
  minio:
    image: minio/minio
    command: 'server /data'
    volumes:
      - ./var/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_ACCESS_KEY_SECRET}
    ports:
      - 9000:9000
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file: .env
    entrypoint: >
      /bin/sh -c "
      set -x
      while ! nc -z minio 9000; echo 'waiting for minio to start' && sleep 0.1; sleep 3;
      /usr/bin/mc config host add minio_docker http://minio:9000 $AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_SECRET;
      /usr/bin/mc mb minio_docker/$S3_BUCKET;
      exit 0;
      "